/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pXo9skAa9of
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function IngredientPanel() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Add Ingredients</CardTitle>
        <CardDescription>Enter the ingredients for your recipe and press enter to add them as tags.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-2">
        <div className="space-y-1">
          <Label htmlFor="ingredient-input">Ingredient</Label>
          <Input id="ingredient-input" placeholder="Enter ingredient" />
        </div>
        <div className="flex flex-wrap gap-2">
          <Badge className="bg-green-100 text-green-800">Eggs</Badge>
          <Badge className="bg-green-100 text-green-800">Milk</Badge>
          <Badge className="bg-green-100 text-green-800">Flour</Badge>
          <Badge className="bg-green-100 text-green-800">Sugar</Badge>
        </div>
      </CardContent>
      <CardFooter>
        <Button>Add Ingredient</Button>
      </CardFooter>
    </Card>
  )
}
